openapi: 3.1.0
info:
  version: '0.1'
  title: StreamFlix
  description: REST API for the StreamFlix streaming platform.
paths: {}
servers:
  # Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/julian-6b4/StreamFlix/0.1